// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_nl8J_r1Qt9QRH0ybdQtu-932TVIpeg',
    appId: '1:625829640098:web:087c7f5d8877c7ca70a4fb',
    messagingSenderId: '625829640098',
    projectId: 'love-e3236',
    authDomain: 'love-e3236.firebaseapp.com',
    storageBucket: 'love-e3236.firebasestorage.app',
    measurementId: 'G-9NJ6VS8XL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPtfmIO6uihFP26-EjTX6u6qSqYUzYzA',
    appId: '1:625829640098:android:2544c2ddb87cb5de70a4fb',
    messagingSenderId: '625829640098',
    projectId: 'love-e3236',
    storageBucket: 'love-e3236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKTXgDi5K4EX92cqFvIuBPTCtUcJck_7k',
    appId: '1:625829640098:ios:40b248b037a739f570a4fb',
    messagingSenderId: '625829640098',
    projectId: 'love-e3236',
    storageBucket: 'love-e3236.firebasestorage.app',
    iosBundleId: 'com.example.loveCook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKTXgDi5K4EX92cqFvIuBPTCtUcJck_7k',
    appId: '1:625829640098:ios:40b248b037a739f570a4fb',
    messagingSenderId: '625829640098',
    projectId: 'love-e3236',
    storageBucket: 'love-e3236.firebasestorage.app',
    iosBundleId: 'com.example.loveCook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG_nl8J_r1Qt9QRH0ybdQtu-932TVIpeg',
    appId: '1:625829640098:web:2b31132a8ed4030d70a4fb',
    messagingSenderId: '625829640098',
    projectId: 'love-e3236',
    authDomain: 'love-e3236.firebaseapp.com',
    storageBucket: 'love-e3236.firebasestorage.app',
    measurementId: 'G-0V3VHYBHZ4',
  );
}
